export const NSR_TYPE = {
    RANDOM: "RANDOM",
    WILDCARD: "WILDCARD",
    SPECIFIC: "SPECIFIC",
}

export const NSR_SUBMIT_TYPE = {
    SEARCH: "SEARCH",
    SEARCH_RESERVE: "SEARCH & RESERVE",
}


export const NUMBER_STATUS = {
    SPARE: "SPARE",
    UNAVAILABLE: "UNAVAILABLE",
    RESERVED: "RESERVED",
    ASSIGNED: "ASSIGNED",
    SUSPEND: "SUSPEND",
    WORKING: "WORKING",
    DISCONNECT: "DISCONNECT",
    TRANSITIONAL: "TRANSITIONAL",
}

export const PROGRESSING_STATUS = {
    IN_PROGRESS: 'IN PROGRESS',

    // ended
    COMPLETED: 'COMPLETED',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
}

export const TASK_TYPE = {
    NUM: "NUM",
    OTHER: "OTHER",
}

export const PAGE_OPERATION = {
    SEARCH: "SEARCH",
    RESERVE: "RESERVE",
    QUERY: "QUERY",
    UPDATE: "UPDATE",
    RETRIEVE: "RETRIEVE",
    DISCONNECT: "DISCONNECT",
    SPARE: "SPARE",
    CHANGE: "CHANGE",
    CONVERT: "CONVERT",
}

export const TASK_ACTION = {
    SEARCH: "SEARCH",
    RESERVE: "RESERVE",
    UPDATE: "UPDATE",
    RETRIEVE: "RETRIEVE",
    DISCONNECT: "DISCONNECT",
    SPARE: "SPARE",
    CHANGE: "CHANGE",
    CONVERT: "CONVERT",
}
