export const PERMISSIONS = {
  // admin privileges
  READ_ROLE: 1,
  WRITE_ROLE: 2,

  READ_USER: 3,
  WRITE_USER: 4,

  READ_COMPANY: 5,
  WRITE_COMPANY: 6,

  READ_SOMOS_USER: 7,
  WRITE_SOMOS_USER: 8,

  READ_ID_RO: 9,
  WRITE_ID_RO: 10,

  READ_SQL_SCRIPT: 11,
  WRITE_SQL_SCRIPT: 12,

  // customer privileges
  CUSTOMER_ADMIN_DATA: 101,
  POINT_ADMIN_DATA: 102,

  TEMPLATE_ADMIN_DATA: 111,
  TEMPLATE_RECORD_LIST: 112,

  SEARCH_NUMBER: 121,
  NUMBER_LIST: 122,
  RESERVE_NUMBER_LIST: 123,
  NUMBER_QUERY: 124,
  ONE_CLICK_ACTIVATE: 125,

  MULTI_DIAL_NUMBER_QUERY: 141,
  MULTI_DIAL_NUMBER_DISCONNECT: 142,
  MULTI_DIAL_NUMBER_SPARE: 143,
  MULTI_DIAL_NUMBER_RESP_ORG_CHANGE: 144,
  MULTI_CONVERSION_TO_POINTER_RECORD: 145,
  AUTO_RESERVE_NUMBERS: 146,
  TROUBLE_REFERRAL_NUMBER_QUERY: 147,

  RESP_ORG_INFORMATION: 161,
  ROC_SUBMIT_REQUEST: 171,
  ROC_CHANGE_REQUEST: 172,
  ROC_LOA_UPLOAD: 173,
  ROC_SUBSCRIBER_NOTIFICATIONS: 174,
  ROC_RESEND_SUBSCRIBER_NOTIFICATIONS: 175,

  SQL_SCRIPT_EXECUTION_RECORD: 191,
  USER_ACTIVITY: 195,
  TASK_TRACKING: 196,
}
